version: '3.9'
services:
  app:
    build: .
    container_name: wwebjs-bot
    restart: unless-stopped
    env_file: .env
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"   # /health, /qr
    volumes:
      - wwebjs_auth:/app/.wwebjs_auth
    shm_size: 1gb

  postgres:
    image: postgres:16
    container_name: wwebjs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whatsapp_bot
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
  wwebjs_auth:
